name: Pull Request Template Validation
on:
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled]

jobs:
  pr-template-validation:
    name: Validates if PR title and body matches template
    runs-on: ubuntu-latest
    # Don't run on PRs labeled as exception
    if: ${{ !contains(github.event.*.labels.*.name, 'skip-pr-template-validation') }}
    steps:
      - name: Validate PR Title & Body
        uses: nowNick/pr-template-validator@main
        with:
          title-contains: 'XYZ-'
          body-regex: 'ABC-\d+'
            
